apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-eu-west-1b
mountOptions:
- debug
parameters:
  type: io1
  zone: "eu-west-1b"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
